### ISSUE TITLE
ModuleNotFoundError: No module named 'blinker._saferef'

### ISSUE THREAD

**Issue by sayatbekbolat** [oxylabs/selenium-proxy-integration-python#10]
python version 3.10
MacOS m1 14.1.2 (23B92)

selenium-wire==5.1.0
webdriver-manager==4.0.1

`Traceback (most recent call last):
  File "/Documents/projects/selenium/main.py", line 4, in <module>
    from seleniumwire import webdriver
  File "/Documents/projects/selenium/.venv/lib/python3.10/site-packages/seleniumwire/webdriver.py", line 28, in <module>
    from seleniumwire import backend, utils
  File "/Documents/projects/selenium/.venv/lib/python3.10/site-packages/seleniumwire/backend.py", line 4, in <module>
    from seleniumwire.server import MitmProxy
  File "/Documents/projects/selenium/.venv/lib/python3.10/site-packages/seleniumwire/server.py", line 5, in <module>
    from seleniumwire.handler import InterceptRequestHandler
  File "/Documents/projects/selenium/.venv/lib/python3.10/site-packages/seleniumwire/handler.py", line 5, in <module>
    from seleniumwire import har
  File "/Documents/projects/selenium/.venv/lib/python3.10/site-packages/seleniumwire/har.py", line 11, in <module>
    from seleniumwire.thirdparty.mitmproxy import connections
  File "/Documents/projects/selenium/.venv/lib/python3.10/site-packages/seleniumwire/thirdparty/mitmproxy/connections.py", line 10, in <module>
    from seleniumwire.thirdparty.mitmproxy.net import tls, tcp
  File "/Documents/projects/selenium/.venv/lib/python3.10/site-packages/seleniumwire/thirdparty/mitmproxy/net/tls.py", line 15, in <module>
    import seleniumwire.thirdparty.mitmproxy.options
  File "Documents/projects/selenium/.venv/lib/python3.10/site-packages/seleniumwire/thirdparty/mitmproxy/options.py", line 5, in <module>
    from seleniumwire.thirdparty.mitmproxy import optmanager
  File "/Documents/projects/selenium/.venv/lib/python3.10/site-packages/seleniumwire/thirdparty/mitmproxy/optmanager.py", line 9, in <module>
    import blinker._saferef
ModuleNotFoundError: No module named 'blinker._saferef'
`

**Comment by Alexander-classik** [comment]
Как способ решения:
from seleniumwire import webdriver as seleniumwire_webdriver
from selenium.webdriver.firefox.service import Service
service = Service('./geckodriver.exe')
driver = seleniumwire_webdriver.Firefox(service=service, options=options, seleniumwire_options=proxy_options)
Но при этом возникает другая ошибка

**Comment by shamhi** [comment]
установи библиотеку blinker==1.7.0 (версия должна быть ниже 1.8.*)
